name: BuildAndPublishToDev
on: 
  push:
    branches:    
      - main
      - RELEASES/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        node-version: '14'
    - name: change directory
      run: |
        cd perfanalyzer
    - name: npm install
      run: |
        cd perfanalyzer
        npm install
        cd src
        touch appInsightsConnectionString-ms.js
        touch appInsightsConnectionString.js
        echo 'export const APPINSIGHTS_CONNECTION_MS_STRING=${{ secrets.APPINSIGHTS_CONNECTION_MS_TEST_STRING }}; export const APPINSIGHTS_CONNECTION_MS_CLASSIC_STRING=${{ secrets.APPINSIGHTS_CONNECTION_MS_CLASSIC_TEST_STRING }}' >>  appInsightsConnectionString-ms.js
        echo 'export const APPINSIGHTS_CONNECTION_STRING=${{ secrets.APPINSIGHTS_CONNECTION_TEST_STRING }}' >>  appInsightsConnectionString.js
        cd ..
        tsc index.ts
        cd ..
  installs:
    runs-on: ubuntu-latest
    steps:
    - name: npm install tfx cli
      run: |
        npm install -g tfx-cli
  bump-version:
    steps:
    runs-on: ubuntu-latest  
    - name: Increment Version
      run: |
         chmod +x ./publish/increment_version.sh
         ./publish/increment_version.sh
      shell: bash  
  package:
    steps:
    runs-on: ubuntu-latest
    - name: npx tfx package
      run: |
        npx tfx extension create --manifest-globs vss-extension.json
  publish:
    steps:
    runs-on: ubuntu-latest    
    - name: Publish to Dev
      run: |
        tfx extension publish --publisher MishraPrateek --manifest-js vss-extension.dev.json
