name: CICD
on: 
  push:
    branches:    
      - main
      - RELEASES/Enable-Workflows 
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
      with:
        node-version: '14'
    - run: npm install