name: CICD
on: 
  push:
    branches:    
      - main
      - RELEASES/**
jobs:
  checkout:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
      with:
        node-version: '14'
  build:
    - name: change directory
      run: |
        cd perfanalyzer
    - name: npm install
      run: |
        cd perfanalyzer
        npm install
  