name: CICD
on: 
  push:
    branches:    
      - main
      - RELEASES/**
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
      with:
        node-version: '14'
    - name: change directory
      run: |
        cd perfanalyzer
    - name: npm install
      run: |
        cd perfanalyzer
        npm install
        cd src
        touch appInsightsConnectionString-ms.js
        touch appInsightsConnectionString.js
        echo 'export const APPINSIGHTS_CONNECTION_MS_STRING=${{ secrets.APPINSIGHTS_CONNECTION_MS_STRING }}; export const APPINSIGHTS_CONNECTION_MS_CLASSIC_STRING=${{ secrets.APPINSIGHTS_CONNECTION_MS_CLASSIC_STRING }}' >>  appInsightsConnectionString-ms.js
        echo 'export const APPINSIGHTS_CONNECTION_STRING=${{ secrets.APPINSIGHTS_CONNECTION_STRING }}' >>  appInsightsConnectionString.js
        cd ..
        tsc index.ts
  